openapi: 3.0.1
info:
  title: Accounts Read Data Plane
  version: v1
paths:
  '/api/accounts/{address}/balance':
    get:
      tags:
        - Accounts
      summary: Get account balance
      operationId: GetAccountBalance
      parameters:
        - name: address
          in: path
          required: true
          description: the string representing the address          
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseModel'
        '429':
          description: Client Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseModel'
        '503':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseModel'

  '/api/accounts/{address}/txn/page/{pageIndex}':
    get:
      tags:
        - Accounts
      summary: List account transactions info by page
      operationId: ListAccountTransactions
      parameters:
        - name: address
          in: path
          required: true
          description: the string representing the address          
          schema:
            type: string            
        - name: pageIndex
          in: path
          required: true
          description: the interger representing page number
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountTransactionSummaryResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseModel'
        '429':
          description: Client Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseModel'
        '503':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseModel'      
                
components:
  schemas:
    Balance:
      type: object
      properties:
        balance:
          type: object
          nullable: false
        blockNumber:
          type: number
          format: int64
          nullable: false
        blockDate:
          type: string
          format: date-time
          nullable: false          
      additionalProperties: false
    BalanceResponse:
      type: object
      properties:
        result:
          allOf:
            - $ref: '#/components/schemas/Balance'
      additionalProperties: false
    AccountTransactionSummary:
      type: object
      properties:
        hash:
          type: string
          nullable: true
        blockNumber:
          type: number
          format: int64
          nullable: true
        blockHash:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time
        nonce:
          type: object
          nullable: true
        from:
          type: string
          nullable: true
        to:
          type: string
          nullable: true          
        value:
          type: object
          nullable: true
        gas:
          type: object
          nullable: true
        gasPrice:
          type: object
          nullable: true
        transactionType:
          $ref: '#/components/schemas/TransactionType'
        receipt:
          $ref: '#/components/schemas/Receipt'
      additionalProperties: false
    AccountTransactionSummaryResponse:
      type: object
      properties:
        pageCount:
          type: integer
          format: int32
        result:
          type: array
          items:
            $ref: '#/components/schemas/AccountTransactionSummary'
      additionalProperties: false
    TransactionType:
      enum:
        - CoinTransfer
        - NewToken
        - TokenTransfer
        - NewSmartContract
        - SmartContract
      type: string
    Receipt:
      type: object
      properties: 
        type:
          type: object
          nullable: true
        status:
          type: object
          nullable: true
        contractAddress:
          type: string
          nullable: true
        gasUsed:
          type: object          
        cumulativeGasUsed:
          type: object
        effectiveGasPrice:
          type: object        
      additionalProperties: false
    ErrorResponseModel:
      type: object
      properties:
        message:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
      additionalProperties: false
