/*
 * Accounts Read Data Plane
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace dp.read.api.Models
{ 
        /// <summary>
        /// Gets or Sets TransactionType
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum TransactionType
        {
            
            /// <summary>
            /// Enum CoinTransferEnum for CoinTransfer
            /// </summary>
            [EnumMember(Value = "CoinTransfer")]
            CoinTransferEnum = 1,
            
            /// <summary>
            /// Enum NewTokenEnum for NewToken
            /// </summary>
            [EnumMember(Value = "NewToken")]
            NewTokenEnum = 2,
            
            /// <summary>
            /// Enum TokenTransferEnum for TokenTransfer
            /// </summary>
            [EnumMember(Value = "TokenTransfer")]
            TokenTransferEnum = 3,
            
            /// <summary>
            /// Enum NewSmartContractEnum for NewSmartContract
            /// </summary>
            [EnumMember(Value = "NewSmartContract")]
            NewSmartContractEnum = 4,
            
            /// <summary>
            /// Enum SmartContractEnum for SmartContract
            /// </summary>
            [EnumMember(Value = "SmartContract")]
            SmartContractEnum = 5
        }
}
